---
title: "BigSimulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BigSimulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
library(parlrdev)
library(tidyverse)
library(knitr)
library(kableExtra)
```


```{r simulation}

n1 <- 100000
n1_vals <- n1
n2_list <- list(1:1000, 
                1001:2000)
n2 <- max(do.call(max, n2_list))
overlap <- n2/2

show_progress <- T
fast = F
R <- 10

m <- c(.01, .99, .01, .99, .01, .99, .01, .99, .01, .99, .01, .99)

u <- c(.999, .001, .999, .001, 
       .999, .001, .999, .001, .999, .001, .999, .001)


levels <- c(2, 2, 2, 2, 2, 2)


# S <- 1000; burn <- S * .1
# m_prior <- u_prior <- rep(1, length(m))
# alpha <- beta <- 1
results_bk_samps <- matrix(NA, nrow = length(n1_vals), ncol = 4)
results_sad_samps <- matrix(NA, nrow = length(n1_vals), ncol = 4)
results_bk_samps_resolved <- matrix(NA, nrow = length(n1_vals), ncol = 4)
double_matches <- numeric(length(n1_vals))

for(i in seq_along(n1)){
  
  #Simulate Data
  # n1 <- n1_vals[i]
  # n2 <- n2_vals[i]
  # overlap <- n2/2
  # cd <- SimulateComparisonsFast(m, u, levels, n1, n2, overlap)
  # cd <- SimulateComparisonsHash(m, u, levels, n1, n2, overlap)
  cd <- SimulateBig(m, u, levels, n1, n2_list, overlap)
  Ztrue <- cd[[1]][[5]]
  
  #parlr method
  ptm <- proc.time()
  Zchain <- BKSimple_hash2_big(cd, R = R)
  #Zchain <- BKSimple_hash2(cd, R = R)
  elapsed <- proc.time() - ptm
  #Zhat <- BRL::linkRecords(Zchain, n1, 1, 1, 2, Inf)
  Zhat <- LinkRecordsBK(Zchain, n1, 1, 1, 2, Inf)
  eval_simple <- GetEvaluations(Zhat[[1]], Ztrue, n1)
  results_bk_samps[i, ] <- c(eval_simple, elapsed[3])
  double_matches[i] <- sum(duplicated(Zhat[[1]]))
  
  Zhat_resolved <- ResolveConflicts(Zhat)
  eval_resolved <- GetEvaluations(Zhat_resolved, Ztrue, n1)
  results_bk_samps_resolved[i, ] <- c(eval_resolved, elapsed[3])
  
  
  #Sadinle 2017 Method
  # ptm <- proc.time()
  # Zchain <- BRL::bipartiteGibbs(cd)
  # elapsed <- proc.time() - ptm
  # Zhat <- BRL::linkRecords(Zchain[[1]], n1, 1, 1, 2, Inf)
  # eval <- GetEvaluations(Zhat, Ztrue, n1)
  # results_sad_samps[i,] <- c(eval, elapsed[3])
  
  print(i)
}

list(BK = results_bk_samps,
     BK_resolved = results_bk_samps_resolved)

double_matches/n2
```
