---
title: "elsalvador_small_P"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{elsalvador_small_P}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

devtools::load_all()
library(parlrdev)
library(tidyverse)
library(knitr)
library(kableExtra)
library(RColorBrewer)
```

```{r}
rm(list=ls())
set.seed(2)
R <- NULL
show_progress <- T
fast <- F
S <- 1000
iter_count <- seq_len(S)

cd <- readRDS("../data/comparison_elsalvador_smallP.rds")
nA <- cd$n1
nB <- cd$n2
levels <- cd[[4]]
P <- prod(levels) 
var_names <- cd$compFields[,1]
ptm <- proc.time()
Zchain_fabl <- BKSimple_hash2(cd, S = S, R = R, show_progress = T, all_patterns = FALSE)
elapsed_fabl <- proc.time() - ptm
Zchain_fabl[[4]]
Zhat_fabl <- LinkRecordsBK(Zchain_fabl[[1]], nA, 1, 1, 2, Inf)
Zhat_fabl_partial <- LinkRecordsBK(Zchain_fabl[[1]], nA, 1, 1, 2, .1)

overlap_fabl <- sum(Zhat_fabl[[1]] < nA + 1)
results_fabl <- c(overlap_fabl, elapsed_fabl[3])

Zhat_resolved <- ResolveConflicts(Zhat_fabl)
overlap_resolved <- sum(Zhat_resolved < nA + 1)
#DID_resolved <- nA + nB - overlap_resolved
overlap_samples_fabl <- apply(Zchain_fabl[[1]], 2, function(x){
  sum(x < nA + 1)
})
credint_fabl_overlap <- quantile(overlap_samples_fabl - not_one2one_samps, c(.025, .975))
not_one2one_samps <- apply(Zchain_fabl[[1]], 2, function(x){
  sum(duplicated(x[x < nA + 1]))
})
results_fabl_resolved <- c(overlap_resolved, elapsed_fabl[3])
Zhat_fabl_partial_resolved <- ResolveConflicts(Zhat_fabl_partial)
fabl_partial_lower <- sum(Zhat_fabl_partial_resolved < nA + 1 & Zhat_fabl_partial_resolved > 0)
fabl_partial_higher <- sum(Zhat_fabl_partial_resolved == -1)

ptm <- proc.time()
Zchain_sadinle <- BRL::bipartiteGibbs(cd)
elapsed_sadinle <- proc.time() - ptm
Zhat_sadinle <- LinkRecordsBK(Zchain_sadinle[[1]], nA, 1, 1, 2, Inf)
Zhat_sadinle_partial <- LinkRecordsBK(Zchain_sadinle[[1]], nA, 1, 1, 2, .1)
overlap_sadinle <- sum(Zhat_sadinle[[1]] < nA +1)
#DID_sadinle <- nA + nB - overlap_sadinle

overlap_samples_sadinle <- apply(Zchain_sadinle[[1]], 2, function(x){
  sum(x < nA + 1)
})
credint_sadinle_overlap <- quantile(overlap_samples_sadinle, c(.025, .975))

sadinle_partial_lower <- sum(Zhat_sadinle_partial[[1]] < nA + 1 & Zhat_sadinle_partial[[1]] > 0)
sadinle_partial_upper <- sum(Zhat_sadinle_partial[[1]] == -1)
results_sadinle <- c(overlap_sadinle, elapsed_sadinle[3])


results_table <- rbind(results_fabl_resolved,
                       results_sadinle)
colnames(results_table) <- c("Overlap", "time (sec)")
rownames(results_table) <- c("fabl",
                             "BRL")
results_image <- results_table %>%
  kable(caption = paste("Linkage Results with P = ", paste(P), "patterns"), digits = 3) %>%
  kable_classic() %>%
  kable_styling(full_width = F)

results_image

# as_image(results_image, file = "../notes/figures/el_salvador/time_table_small_P2.png")


```


```{r}
bayes <- results_table[,1]
method <- rownames(results_table)
bayes_df <- data.frame(bayes, method)
bayes_df <- bayes_df[c(2, 3), ]

method <- c(rep("fabl", S), rep("BRL", S))
overlap <- c(overlap_samples_fabl, overlap_samples_sadinle)
iteration <- c(iter_count, iter_count)
df <- data.frame(overlap, method)

df %>% 
  ggplot(aes(y = overlap, fill = method)) +
  geom_histogram() + 
  geom_hline(yintercept = bayes_df$bayes,
             color = brewer.pal(n = 3, name = "Set1")[1:2]) + 
  geom_hline(yintercept = bayes[1],
             color = brewer.pal(n = 3, name = "Set1")[2],
             linetype = "longdash") +
  labs(y = "Overlap",
       x = NULL,
       title = "Posterior Distribution of Overlap",
       fill = "Method") +
  coord_flip() + 
  theme_bw() + 
  scale_fill_brewer(palette="Set1")

#ggsave("../notes/figures/el_salvador/overlap_distribution_smallP_bayes.png")

overlap_trace <- df %>% 
  filter(method == "fabl") %>% 
  ggplot(aes(x = iter_count, y = overlap)) +
  geom_line() + 
  labs(x = NULL, 
       y = NULL) +
  theme_bw()

ggsave("../notes/figures/el_salvador/overlap_trace.png")

bayes_df$bayes <- nA + nB - bayes_df$bayes
df$overlap <- nA + nB - df$overlap

df %>% 
  ggplot(aes(y = overlap, fill = method)) +
  geom_histogram() + 
  geom_hline(yintercept = bayes_df$bayes,
             color = brewer.pal(n = 3, name = "Set1")[1:2]) + 
  # geom_hline(yintercept = nA + nB - bayes[1],
  #            color = brewer.pal(n = 3, name = "Set1")[2],
  #            linetype = "longdash") +
  labs(y = "Documented Identifiable Deaths",
       x = NULL,
       fill = "Method") +
  coord_flip() + 
  theme_bw() + 
  scale_fill_brewer(palette="Set1")

ggsave("../notes/figures/el_salvador/DID_distribution_smallP_bayes.png")
```

```{r}
#samps <- Zchain_fabl$m
ProcessChain <- function(samps){
  avg <- apply(samps, 1, mean)
  upper <- apply(samps, 1, function(x){
    quantile(x, .975)
  })
  lower <- apply(samps, 1, function(x){
    quantile(x, .025)
  })
  params <- factor(unlist(sapply(levels, seq_len)))
  field <- factor(unlist(mapply(function(x, y) {
    rep(x, y)
  }, x = var_names, y = levels)), levels = var_names)
  
  data.frame(params, field, avg, upper, lower)
}
m_fabl <- ProcessChain(Zchain_fabl$m)
m_fabl$method <- "fabl"
m_sadinle <- ProcessChain(Zchain_sadinle$m)
m_sadinle$method <- "BRL"
df <- rbind(m_fabl, m_sadinle)
df %>% 
  ggplot(aes(x = params, y = avg,
             ymin = lower, ymax = upper, color = method)) +
  geom_pointrange(position = position_dodge2(width = .5)) +
  facet_wrap(~field, scales = "free_x") + 
  labs(y = "Probability",
       x = "Agreement Level",
       color = "Method") + 
  theme_bw() + 
  scale_color_brewer(palette="Set1")

ggsave("../notes/figures/el_salvador/m_posterior_smallP.png")

m_tidy <- lapply(seq_len(dim(Zchain_fabl$m)[1]), function(x){
  data.frame(Zchain_fabl$m[x, ], m_fabl[x, 1], m_fabl[x, 2])
}) %>% 
  do.call(rbind, .)

colnames(m_tidy) <- c("value", "level", "field")
m_tidy <- m_tidy %>% 
  group_by(field, level) %>% 
  mutate(iteration = row_number()) %>% 
  ungroup()

m_trace <- m_tidy %>% 
  ggplot(aes(x = iteration, y = value)) +
  facet_grid(level ~ field) + 
  geom_line() +
  labs(x = NULL, y = NULL) +
  scale_x_continuous(labels = NULL, breaks = NULL)

ggsave("../notes/figures/el_salvador/m_trace.png", plot = m_trace)

u_fabl <- ProcessChain(Zchain_fabl$u)
u_fabl$method <- "fabl"

u_tidy <- lapply(seq_len(dim(Zchain_fabl$u)[1]), function(x){
  data.frame(Zchain_fabl$u[x, ], u_fabl[x, 1], u_fabl[x, 2])
}) %>% 
  do.call(rbind, .)

colnames(u_tidy) <- c("value", "level", "field")
u_tidy <- u_tidy %>% 
  group_by(field, level) %>% 
  mutate(iteration = row_number()) %>% 
  ungroup()

u_trace <- u_tidy %>% 
  ggplot(aes(x = iteration, y = value)) +
  facet_grid(level ~ field, scales = "free_y") + 
  geom_line() +
  labs(x = NULL, y = NULL) +
  scale_x_continuous(labels = NULL, breaks = NULL)

ggsave("../notes/figures/el_salvador/u_trace.png", plot = u_trace)
  
```

## Comparing Mixing

```{r}
find <- which(Zhat_fabl[[1]] == 2776)
probs <- Zhat_fabl[[2]][find]
dups_fabl <- Zchain_fabl[[1]][find,]
dups_sadinle <- Zchain_sadinle[[1]][find, ]
dups_sadinle[dups_sadinle > nA + 2] <- nA + 1


dups_fabl <- cbind(dups_fabl, c("Rosa", "Rosa Maria") , "fabl")
dups_sadinle <- cbind(dups_sadinle, c("Rosa", "Rosa Maria") , "BRL")
df <- data.frame(rbind(dups_fabl, dups_sadinle[,-(1:100)]))
names(df)[c(901, 902)] <- c("record", "method")
df_mixing <- df %>% 
  pivot_longer(1:900) %>% 
  group_by(record, method) %>% 
  mutate(iter = row_number()) %>% 
  filter(iter < 400) %>% 
  mutate(type_match = case_when(
    value == 2776 ~ "Best Match (Rosa Maria)",
    value > nA ~ "No match",
    TRUE  ~ "Match to other record"
  ))




df_mixing %>% 
  ggplot(aes(x = iter, y = value, color = type_match)) +
  geom_point(size = .9) +
  facet_grid(record~method) + 
  #scale_x_continuous(labels = NULL, breaks = NULL) + 
  labs(x = "Gibbs Iterations",
       y = expression(Z[j]),
       color = "Type of Match") +
  theme_bw(base_size = 8)+
  scale_color_brewer(palette="Set1") +
  theme(legend.position="bottom") +
  guides(color=guide_legend(nrow=2,byrow=TRUE))

ggsave("../notes/figures/el_salvador/bad_mixing.png")
```

