---
title: "elsalvador1"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{elsalvador1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
library(parlrdev)
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r}
rm(list=ls())
gc()
set.seed(2)
R <- NULL
show_progress <- T
fast <- F
S <- iter <- 1000
burn <- S * .1
iter_count <- seq_len(S)

cd <- readRDS("../data/comparison_elsalvador.rds")
nA <- cd$n1
nB <- cd$n2
levels <- cd[[4]]
P <- prod(levels) 
var_names <- cd$compFields[,1]
ptm <- proc.time()
Zchain_fabl <- BKSimple_hash2(cd, S = S, R = R, show_progress = T, all_patterns = FALSE)
elapsed_fabl <- proc.time() - ptm
Zchain_fabl[[4]]
Zhat_fabl <- LinkRecordsBK(Zchain_fabl[[1]], nA, 1, 1, 2, Inf)
overlap_fabl <- sum(Zhat_fabl[[1]] < nA + 1)
results_fabl <- c(overlap_fabl, elapsed_fabl[3])

Zhat_resolved <- ResolveConflicts(Zhat_fabl)
overlap_resolved <- sum(Zhat_resolved < nA + 1)
DID_resolved <- nA + nB - overlap_resolved
overlap_samples_fabl <- apply(Zchain_fabl[[1]], 2, function(x){
  sum(x < nA + 1)
})
not_one2one_samps <- apply(Zchain_fabl[[1]], 2, function(x){
  sum(duplicated(x[x < nA + 1]))
})
results_fabl_resolved <- c(DID_resolved, elapsed_fabl[3])


ptm <- proc.time()
Zchain_sadinle <- BRL::bipartiteGibbs(cd)
elapsed_sadinle <- proc.time() - ptm
Zhat_sadinle <- LinkRecordsBK(Zchain_sadinle[[1]], nA, 1, 1, 2, Inf)
overlap_sadinle <- sum(Zhat_sadinle[[1]] < nA +1)
DID_sadinle <- nA + nB - overlap_sadinle

overlap_samples_sadinle <- apply(Zchain_sadinle[[1]], 2, function(x){
  sum(x < nA + 1)
})

results_sadinle <- c(DID_sadinle, elapsed_sadinle[3])

results_table <- rbind(results_fabl_resolved,
                       results_sadinle)
colnames(results_table) <- c("DID", "time (sec)")
rownames(results_table) <- c("fabl",
                             "BRL")
results_image <- results_table %>%
  kable(caption = paste("Linkage Results with P = ", paste(P), "patterns"), digits = 3) %>%
  kable_classic() %>%
  kable_styling(full_width = F)

results_image

as_image(results_image, file = "../notes/figures/el_salvador/time_table_big_P2.png")



```

```{r}
method <- c(rep("parlr", iter - burn), rep("sadinle", iter - burn))
overlap <- c(overlap_samples_fabl, overlap_samples_sadinle)
df <- data.frame(overlap, method)

df %>% 
  ggplot(aes(y = overlap, fill = method)) +
  geom_histogram() + 
  labs(y = "Overlap",
       x = NULL,
       title = "Posterior Distribution of Overlap",
       color = "Method") +
  coord_flip() + 
  theme_bw() + 
  scale_fill_brewer(palette="Set1")

#ggsave("../notes/figures/el_salvador/overlap_distribution_bigP.png")
```

```{r}
#samps <- Zchain_parlr$m
ProcessChain <- function(samps){
  avg <- apply(samps, 1, mean)
  upper <- apply(samps, 1, function(x){
    quantile(x, .975)
  })
  lower <- apply(samps, 1, function(x){
    quantile(x, .025)
  })
  params <- factor(unlist(sapply(levels, seq_len)))
  field <- factor(unlist(mapply(function(x, y) {
    rep(x, y)
  }, x = var_names, y = levels)), levels = var_names)
  
  data.frame(params, field, avg, upper, lower)
}
m_parlr <- ProcessChain(Zchain_parlr$m)
m_parlr$method <- "parlr"
m_sadinle <- ProcessChain(Zchain_sadinle$m)
m_sadinle$method <- "sadinle"
df <- rbind(m_parlr, m_sadinle)
df %>% 
  ggplot(aes(x = params, y = avg,
             ymin = lower, ymax = upper, color = method)) +
  geom_pointrange(position = position_dodge2(width = .5)) +
  facet_wrap(~field, scales = "free_x") + 
  labs(title = paste("Distributions of m parameters, P =", paste(P), "Patterns"),
       y = "Probability",
       x = "Agreement Level",
       color = "Method") + 
  theme_bw() + 
  scale_color_brewer(palette="Set1")

#ggsave("../notes/figures/el_salvador/m_posterior_bigP.png")


```


