---
title: "nltcs_linkage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{nltcs_linkage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#devtools::install()
devtools::load_all()
library(parlrdev)
library(tidyverse)
library(BRL)
library(furrr)
```

```{r}
S <- 900
nltcs <- read.csv("../data/proc_nltcs.csv")
df82 <- nltcs %>% 
  filter(FILE == 82) %>% 
  select(-FILE, -SEQ) %>% 
  mutate(unique_ID = str_sub(REC, start = 3L),
         DOB_DAY = str_pad(DOB_DAY, 2, pad = "0"), 
         DOB_MONTH = str_pad(DOB_MONTH, 2, pad = "0"), 
         DOB_YEAR = str_pad(DOB_YEAR, 2, pad = "0"),
         STATE = str_pad(STATE, 2, pad = "0"),
         REGOFF = str_pad(REGOFF, 2, pad = "0")) %>% 
  #unite(dob, 2:4, sep = "") %>% 
  unite(location, c(STATE, REGOFF), sep = "")
  

df89 <- nltcs %>% 
  filter(FILE == 89) %>% 
  select(-FILE, -SEQ) %>% 
  mutate(unique_ID = str_sub(REC, start = 3L)) %>% 
  mutate(unique_ID = str_sub(REC, start = 3L),
         DOB_DAY = str_pad(DOB_DAY, 2, pad = "0"), 
         DOB_MONTH = str_pad(DOB_MONTH, 2, pad = "0"), 
         DOB_YEAR = str_pad(DOB_YEAR, 2, pad = "0"),
         STATE = str_pad(STATE, 2, pad = "0"),
         REGOFF = str_pad(REGOFF, 2, pad = "0")) %>% 
 # unite(dob, 2:4, sep = "") %>% 
  unite(location, c(STATE, REGOFF), sep = "")

# df82 <- df82[-c(1:2000), ]
# df89 <- df89[-c(1:2000), ]

nA <- nrow(df82)
nB <- nrow(df89)
Ztrue <- sapply(df89$unique_ID, function(x){
  match <- which(df82$unique_ID == x)
  if (length(match) == 0){
    match <- nA + 1
  }
  match
}) %>% 
  unname()

chunks <- 30
chunk_size <- ceiling(dim(df89)[1]/chunks)
chunk_id <- rep(1:chunks, each = chunk_size)[1:dim(df89)[1]]
fields <- 1:5
df89_partition <- split(df89, chunk_id)
df1 <- df82
df2 <- df89_partition[[1]]
```


```{r}

HashRecords <- function(df2){
  cd <- CompareNLTCS2(df82, df2)
  patterns <- GetUniquePatterns2(cd, R = 10)
  patterns
}

patterns_hashed <- lapply(df89_partition, HashRecords)
#test <- HashRecords(df2)
```

```{r combine-results}
counts_big <- Reduce(`+`, map(patterns_hashed, ~.x[[2]]))

counts_per_rec_big <- patterns_hashed %>%
    map(`[[`, 3) %>%
    flatten()

  hash_list_big <- patterns_hashed %>%
    map(`[[`, 4) %>%
    flatten()


  #n2 <- max(do.call(max, n2_list))

  # Ztrue <- patterns_big %>%
  #   map(`[[`, 5) %>%
  #   do.call(c, .)

  #possible_patterns <- GetPossiblePatternsSad_sep(levels)

  comparisons <- list(indicators = NULL,
                      n1 = dim(df82)[1],
                      n2 = dim(df89)[1],
                      nDisagLevs = c(2, 2, 2, 2, 3),
                      Ztrue = Ztrue)

  patterns <- list(patterns_hashed[[1]][[1]],
       counts_big,
       counts_per_rec_big,
       hash_list_big)

  cd <- list(comparisons, patterns)
  
  
  Zchain %>% 
    apply(., 2, function(x){
      x < nA +1
    }) %>% 
    colSums()
  
  chain$m %>% 
    rowMeans()
```

```{r load_hash}
#saveRDS(cd, file = "../data/ntlcs_hash4.rds")
cd <- readRDS(file = "../data/ntlcs_hash4.rds")
```


```{r Gibbs}
ptm <- proc.time()
chain <- BKSimple_hash2_big(cd)
elapsed <- proc.time() - ptm 
Zchain <- chain$Z
nA <- cd[[1]][[2]]
nB <- cd[[1]][[3]]
Zhat <- LinkRecordsBK(Zchain, nA, 1, 1, 2, Inf)
post_probs <- Zhat[[2]]
Zhat_resolved <- ResolveConflicts(Zhat)
eval <- GetEvaluations(Zhat_resolved, Ztrue, nA)
Zhat <- Zhat[[1]]
overlap_samps <- apply(Zchain, 2, function(x){
  sum(x < nA + 1)
})
overlap_samps %>% 
  unlist() %>% 
  unname() %>% 
  quantile(., c(.025, .975))


# png(file="../notes/figures/nltcs/postprob_hist4.png")
# hist(post_probs)
# dev.off()

hist(post_probs)
#hist(overlap_samps)
# hist(Zhat[[2]][Zhat[[1]] < nA + 1])
```



```{r}
bayes_initial <- sum(Zhat < nA + 1)
bayes_resolved <- sum(Zhat_resolved < nA + 1)
overlap_samps <- data.frame(overlap_samps)

#not a good image
overlap_samps %>% 
  ggplot(aes(x = overlap_samps)) +
  geom_histogram() + 
  geom_vline(xintercept = bayes_resolved) + 
  labs(x = NULL, y = NULL) + 
  theme_bw()

ggsave("../notes/figures/nltcs/overlap_posterior4.png")
```

```{r m_and_u}
var_names <- colnames(df82)[fields]
levels <- cd[[1]][[4]]
ProcessChain <- function(samps){
  avg <- apply(samps, 1, mean)
  upper <- apply(samps, 1, function(x){
    quantile(x, .975)
  })
  lower <- apply(samps, 1, function(x){
    quantile(x, .025)
  })
  params <- factor(unlist(sapply(levels, seq_len)))
  field <- factor(unlist(mapply(function(x, y) {
    rep(x, y)
  }, x = var_names, y = levels)), levels = var_names)
  
  data.frame(params, field, avg, upper, lower)
}
m_summary <- ProcessChain(chain$m)
u_summary <- ProcessChain(chain$u)

m_summary %>% 
  ggplot(aes(x = params, y = avg,
             ymin = lower, ymax = upper)) +
  geom_pointrange(position = position_dodge2(width = .5)) +
  facet_wrap(~field, scales = "free_x") + 
  labs(y = "Probability",
       x = "Agreement Level") + 
  theme_bw()

ggsave("../notes/figures/nltcs/m_posterior4.png")

u_summary %>% 
  ggplot(aes(x = params, y = avg,
             ymin = lower, ymax = upper)) +
  geom_pointrange(position = position_dodge2(width = .5)) +
  facet_wrap(~field, scales = "free_x") + 
  labs(y = "Probability",
       x = "Agreement Level") + 
  theme_bw()

#ggsave("../notes/figures/el_salvador/m_posterior_smallP.png")

```

```{r}
Zhat_bind <- cbind(Zhat, post_probs)
bouncing_matches <- which(Zhat_bind[, 2] < .5)
examples <- Zhat_bind[bouncing_matches, ]
rownames(examples) <- bouncing_matches
colnames(examples) <- c("Zhat", "probability")

probs_for_bouncing_matches <- lapply(bouncing_matches, function(x){
  Zchain[x, ] %>% 
    table()/S
})

names(probs_for_bouncing_matches) <- bouncing_matches

#sapply(probs_for_bouncing_matches, length) - 1

#probs_for_bouncing_matches["8"]
  
```

```{r}
df89_true <- df89 %>% 
  filter(Ztrue < nA + 1)

df82_true <- df82[Ztrue[Ztrue < nA + 1], ]
df89_true$unique_ID == df82_true$unique_ID

MLEs <- sapply(1:6, function(x){
  sum(df82_true[, x] == df89_true[, x]) / nrow(df82_true)
})

MLEs
```

```{r}
df82 %>% 
  mutate(REGOFF = as.factor(REGOFF),
         STATE = as.factor(STATE)) %>% 
  group_by(STATE, REGOFF) %>% 
  count()
```
