---
title: "Sadinle_speed_fixed_nB"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Sadinle_speed_fixed_nB}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

devtools::load_all()
library(parlrdev)
library(tidyverse)
library(knitr)
library(kableExtra)
```



```{r}

rm(list=ls())
gc()
set.seed(3)

n1_vals <- c(500, 1000, 2000, 3000, 4000, 5000, 6000, 7000)
n2 <- 500
show_progress <- T
fast = F

m <- c(.01, .09, .90, .01, .09, .90, .01, .09, .90, .01, .09, .90)

u <- c(.96, .03, .01, .96, .03, .01, 
       .96, .03, .01, .96, .03, .01)


levels <- c(3, 3, 3, 3)


# S <- 1000; burn <- S * .1
# m_prior <- u_prior <- rep(1, length(m))
# alpha <- beta <- 1
parlr_speed_samps2 <- matrix(NA, nrow = length(n1_vals), ncol = 5)
sad_speed_samps2 <- matrix(NA, nrow = length(n1_vals), ncol = 5)

for(i in seq_along(n1_vals)){
  
  #Simulate Data
  n1 <- n1_vals[i]
  overlap <- n2/2
  
  cd <- SimulateComparisonsFast(m, u, levels, n1, n2, overlap)
  Ztrue <- cd$Ztrue
  
  #parlr method
  ptm <- proc.time()
  Zchain <- fabl_gibbs(cd, all_patterns = F)
  elapsed <- proc.time() - ptm
  hash_time <- Zchain[[4]]
  Zchain <- Zchain[[1]]
  Zhat <- BRL::linkRecords(Zchain, n1, 1, 1, 2, Inf)
  eval <- GetEvaluations(Zhat, Ztrue, n1)
  parlr_speed_samps2[i,] <- c(eval, elapsed[3], hash_time)
  
  #Sadinle 2017 Method
  ptm <- proc.time()
  Zchain <- BRL::bipartiteGibbs(cd)
  elapsed <- proc.time() - ptm
  Zhat <- BRL::linkRecords(Zchain[[1]], n1, 1, 1, 2, Inf)
  eval <- GetEvaluations(Zhat, Ztrue, n1)
  sad_speed_samps2[i,] <- c(eval, elapsed[3], hash_time)
  
  print(i)
}

# list(BK = parlr_speed_samps2,
#      Sadinle = sad_speed_samps2)
```

```{r}



parlr_df <- data.frame(parlr_speed_samps2, n1_vals, "fabl")
names(parlr_df) <- c("recall", "precision", "fmeasure", "time", "hash_time", "nA", "method")
sadinle_df <- data.frame(sad_speed_samps2, n1_vals, "BRL")
names(sadinle_df) <- c("recall", "precision", "fmeasure", "time", "hash_time", "nA",  "method")

df<- rbind(parlr_df, sadinle_df)

saveRDS(df, "../data/speed_sim_fixed_nB2")
#df <- readRDS("../data/speed_sim_fixed_nB2")

speed_plot_fixed_nB <- df %>% 
  ggplot(aes(x = nA, y = time, color = method)) +
  geom_line(size = .8) +
  geom_point(size = 1.4) + 
  labs(x = expression(n[A]),
       y = NULL,
       #y = "Time (seconds)",
       color = "Method") +
  theme_bw(base_size = 14) + 
  #theme(legend.position = "bottom") +
  scale_color_brewer(palette="Set1")

speed_plot_fixed_nB

ggsave(filename = "../notes/figures/speed_plot_fixed_nB2_new.png", plot = speed_plot_fixed_nB)


# results_df <- df %>% 
#   pivot_longer(cols = 1:4, names_to = "metric") %>% 
#   group_by(method, metric) %>% 
#   summarize(avg = mean(value),
#             lower = quantile(value, .2),
#             upper = quantile(value, .8),
#             .groups = "drop")
#results_df
# simple_dist_table <- results_df %>%
#   kable(digits = 3,
#         caption = "Results for Simpler Distributions (Full)") %>%
#   kable_classic() %>%
#   kable_styling(full_width = F)
  #as_image(file = "../notes/figures/simple_dist_table.png")
```
```{r}
Zchain$pi
```

