---
title: "Sadinle_accuracy"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Sadinle_accuracy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(devtools)
load_all()
library(parlrdev)
library(tidyverse)
rm(list = c("hash_field"))
```


```{r}
files <- list.files(path = "../data/SimulationDatafiles", full.names = T)
all_patterns = TRUE
R = NULL


overlap_vals <- c(50, 250, 450)

fabl_acc_samps <- array(NA, dim = c(length(files), 5, 3))
fabl_acc_samps_resolved <- array(NA, dim = c(length(files), 5, 3))
sad_acc_samps <- array(NA, dim = c(length(files), 5, 3))

fabl_acc_samps2 <- array(NA, dim = c(length(files), 5, 3))
fabl_acc_samps_resolved2 <- array(NA, dim = c(length(files), 5, 3))
sad_acc_samps2 <- array(NA, dim = c(length(files), 5, 3))

for(j in seq_along(overlap_vals)){
  
  overlap <- overlap_vals[j]
  
for(i in seq_along(files)){

records <- read_csv(files[i], col_types = cols())
records$file <- rep(2:1, length.out = dim(records)[1])

records <- records %>% 
  janitor::clean_names() %>% 
  mutate(rec_id = as.numeric(str_extract(rec_id, "\\d{3}")) + 1)

n1 <- 500
n2 <- 500
#overlap <- n2/2

Ztrue <- n1 + 1:n2
Ztrue[1:overlap] <- 1:overlap

file1 <- records %>% 
  filter(file ==1,
         rec_id <= n1) %>% 
  select(-rec_id) %>% 
  as.matrix(.) %>% 
  data.frame(.) %>% 
  mutate(occup = as.numeric(occup))

file2 <- records %>% 
  filter(file == 2,
         rec_id %in% c(1:overlap, (n1 +1):(1000 - overlap))) %>% 
  select(-rec_id) %>% 
  as.matrix() %>% 
  data.frame(.) %>% 
  mutate(occup = as.numeric(occup))

# #old
# cd <- suppressMessages(BRL::compareRecords(file1, file2, c(2, 3, 4, 5), 
#                           types = c("lv", "lv", "bi", "bi")))
# cd[[1]] <- apply(cd[[1]], 2, as.numeric)

cd <- suppressMessages(BRL::compareRecords(file1, file2, c(2, 3, 5, 6), 
                          types = c("lv", "lv", "bi", "bi")))
cd[[1]] <- apply(cd[[1]], 2, as.numeric)

# cd[[1]] <- cd[[1]][, -c(10, 11, 13, 14)]
# cd[[4]] <- c(4, 4, 2, 2)

  #parlr method
  ptm <- proc.time()
  Zchain <- BKSimple_hash2(cd)
  elapsed <- proc.time() - ptm
  Zhat <- LinkRecordsBK(Zchain[[1]], n1, 1, 1, 2, Inf)
  eval <- GetEvaluations(Zhat[[1]], Ztrue, n1)
  
  # Resolution Step
  Zhat_resolved <- ResolveConflicts(Zhat)
  eval_resolved <- GetEvaluations(Zhat_resolved, Ztrue, n1)
  fabl_acc_samps_resolved[i, , j] <- c(eval_resolved, elapsed[3], overlap)
  fabl_acc_samps[i, ,j] <- c(eval, elapsed[3], overlap)
  
  #Partial Estimate
  Zhat <- LinkRecordsBK(Zchain[[1]], n1, 1, 1, 2, .1)
  Zhat <- ResolveConflicts(Zhat)
  eval <- GetEvaluations(Zhat, Ztrue, n1)
  eval[1] <- sum(Zhat == Ztrue & Ztrue > n1) / (sum(Zhat > n1))
  fabl_acc_samps2[i, ,j] <- c(eval, elapsed[3], overlap)
  
  #Sadinle 2017 Method
  ptm <- proc.time()
  Zchain <- BRL::bipartiteGibbs(cd)[[1]]
  Zchain <- Zchain[,101:1000]
  elapsed <- proc.time() - ptm
  Zhat <- BRL::linkRecords(Zchain, n1, 1, 1, 2, Inf)
  eval <- GetEvaluations(Zhat, Ztrue, n1)
  sad_acc_samps[i, ,j] <- c(eval, elapsed[3], overlap)
  
  Zhat <- BRL::linkRecords(Zchain, n1, 1, 1, 2, .1)
  eval <- GetEvaluations(Zhat, Ztrue, n1)
  eval[1] <- sum(Zhat == Ztrue & Ztrue > n1) / (sum(Zhat > n1))
  sad_acc_samps2[i, ,j] <- c(eval, elapsed[3], overlap)
  
  print(i)
}
}
# list(BK = parlr_acc_samps,
#      Sadinle = sad_acc_samps)

```

```{r}
fabl_samps <- rbind(fabl_acc_samps[,,1], fabl_acc_samps[,,2], fabl_acc_samps[,,3])

fabl_samps_resolved <- rbind(fabl_acc_samps_resolved[,,1], fabl_acc_samps_resolved[,,2], fabl_acc_samps_resolved[,,3])

sad_samps <- rbind(sad_acc_samps[,,1], sad_acc_samps[,,2], sad_acc_samps[,,3])
error_level <- rep(rep(c("One Error", "Two Errors", "Three Errors"), each = 100), 3)
error_level <- factor(error_level, levels = c("One Error", "Two Errors", "Three Errors"))
#error_level <- 3
# error_level <- factor(error_level, levels = c("One Error", "Two Errors", "Three Errors"))

fabl_df <- data.frame(fabl_samps, error_level, "fabl")
names(fabl_df) <- c("Recall", "Precision", "Fmeasure", "time", "overlap", "error_level", "method")
fabl_resolved_df <- data.frame(fabl_samps_resolved, error_level, "fabl_resolved")
names(fabl_resolved_df) <- c("Recall", "Precision", "Fmeasure", "time", "overlap", "error_level", "method")
sadinle_df <- data.frame(sad_samps, error_level, "Sadinle17")
names(sadinle_df) <- c("Recall", "Precision", "Fmeasure", "time", "overlap", "error_level",  "method")

df<- rbind(fabl_df, fabl_resolved_df, sadinle_df)

results_df <- df %>%
  pivot_longer(cols = 1:4, names_to = "metric") %>%
  group_by(method, metric, error_level, overlap) %>%
  summarize(avg = mean(value),
            lower = quantile(value, .025),
            upper = quantile(value, .975),
            .groups = "drop") %>%
  filter(metric != "time") %>% 
  mutate(metric = factor(metric, c("Recall", "Precision", "Fmeasure")),
         overlap = case_when(
           overlap == 50 ~ "10% Overlap",
           overlap == 250 ~ "50% Overlap",
           overlap == 450 ~ "90% Overlap"
         ))

saveRDS(results_df, file = "Sadinle_Replication_Results2")
#results_df <- readRDS("Sadinle_Replication_Results2")
results_df <- results_df %>% 
  filter(method != "fabl")

results_df$method[results_df$method == "Sadinle17"] <- "BRL"

results_df$method[results_df$method == "fabl_resolved"] <- "fabl"
acc_plot <- results_df %>% 
  ggplot(aes(x = metric, y = avg,
             ymin  = lower, ymax = upper,
             color = method)) +
  geom_pointrange(position = position_dodge2(width = .5)) + 
  facet_grid(overlap ~ error_level) +
  labs(x = NULL, 
       y = NULL,
       color = "Method") +
  theme_bw(base_size = 10) +
  theme(plot.title = element_text(hjust = .5),
        plot.subtitle = element_text(hjust = .5)) + 
  scale_color_brewer(palette="Set1")

acc_plot

ggsave(filename = "../notes/figures/sadinle_sim_plot2.png",
       plot = acc_plot)
#   
# simple_dist_table <- results_df %>%
#   kable(digits = 3,
#         caption = "Results for Simpler Distributions (Full)") %>%
#   kable_classic() %>%
#   kable_styling(full_width = F)
  #as_image(file = "../notes/figures/simple_dist_table.png")

# simulation_samps <- list(fabl_samps, sad_samps)
# saveRDS(simulation_samps, file = "../data/sadinle_accuracy_samps.rds")
```

```{r}
difference <- fabl_samps_resolved[,-5] - sad_samps[,-5]
difference_df <- data.frame(difference, fabl_samps[,5], error_level)
names(difference_df) <- c("Recall", "Precision", "Fmeasure", "time", "overlap", "error_level")

results_diff_df <- difference_df %>%
  pivot_longer(cols = 1:4, names_to = "metric") %>%
  group_by(metric, error_level, overlap) %>%
  summarize(avg = mean(value),
            lower = quantile(value, .2),
            upper = quantile(value, .8),
            .groups = "drop") %>%
  filter(metric != "time") %>% 
  mutate(metric = factor(metric, c("Recall", "Precision", "Fmeasure")),
         overlap = case_when(
           overlap == 50 ~ "10% Overlap",
           overlap == 250 ~ "50% Overlap",
           overlap == 450 ~ "90% Overlap"
         ))

acc_plot_pairwise <- results_diff_df %>% 
  ggplot(aes(x = metric, y = avg,
             ymin  = lower, ymax = upper)) +
  geom_pointrange() + 
  geom_hline(yintercept = 0, color = "light grey") +
  facet_grid(overlap ~ error_level) +
  labs(x = "Error Level", 
       y = "fabl Minus Sadinle",
       title = "Replication of Sadinle Simulation",
       subtitle = "Pairwise Comparison") +
  theme_bw(base_size = 10) +
  theme(plot.title = element_text(hjust = .5),
        plot.subtitle = element_text(hjust = .5))

acc_plot_pairwise

# ggsave(filename = "../notes/figures/sadinle_pairwise_plot.png",
#        plot = acc_plot_pairwise)

```

```{r}
fabl_samps2 <- rbind(fabl_acc_samps2[,,1], fabl_acc_samps2[,,2], fabl_acc_samps2[,,3])

# fabl_samps_resolved <- rbind(fabl_acc_samps_resolved[,,1], fabl_acc_samps_resolved[,,2], fabl_acc_samps_resolved[,,3])

sad_samps2 <- rbind(sad_acc_samps2[,,1], sad_acc_samps2[,,2], sad_acc_samps[,,3])
error_level <- rep(rep(c("One Error", "Two Errors", "Three Errors"), each = 100), 3)
error_level <- factor(error_level, levels = c("One Error", "Two Errors", "Three Errors"))
#error_level <- 3
# error_level <- factor(error_level, levels = c("One Error", "Two Errors", "Three Errors"))

fabl_df2 <- data.frame(fabl_samps2, error_level, "fabl")
names(fabl_df2) <- c("NPV", "PPV", "Fmeasure", "time", "overlap", "error_level", "method")
# fabl_resolved_df <- data.frame(fabl_samps_resolved, error_level, "fabl_resolved")
# names(fabl_resolved_df) <- c("NPV", "PPV", "Fmeasure", "time", "overlap", "error_level", "method")
sadinle_df2 <- data.frame(sad_samps2, error_level, "Sadinle17")
names(sadinle_df2) <- c("NPV", "PPV", "Fmeasure", "time", "overlap", "error_level",  "method")

df2 <- rbind(fabl_df2, sadinle_df2)
results_df2 <- df2 %>%
  pivot_longer(cols = 1:2, names_to = "metric") %>%
  group_by(method, metric, error_level, overlap) %>%
  summarize(avg = mean(value, na.rm = T),
            lower = quantile(value, .025, na.rm = T),
            upper = quantile(value, .975, na.rm = T),
            .groups = "drop") %>% 
  mutate(metric = factor(metric, c("NPV", "PPV", "Fmeasure")),
         overlap = case_when(
           overlap == 50 ~ "10% Overlap",
           overlap == 250 ~ "50% Overlap",
           overlap == 450 ~ "90% Overlap"
         ))

saveRDS(results_df2, file = "Sadinle_Replication_Results_Partial")

results_df2$method[results_df2$method == "Sadinle17"] <- "BRL"

# results_df$method[results_df$method == "fabl_resolved"] <- "fabl"

acc_plot_partial <- results_df2 %>% 
  ggplot(aes(x = metric, y = avg,
             ymin  = lower, ymax = upper,
             color = method)) +
  geom_pointrange(position = position_dodge2(width = .5)) + 
  facet_grid(overlap ~ error_level) +
  labs(x = NULL, 
       y = NULL,
       color = "Method") +
  theme_bw(base_size = 10) +
  theme(plot.title = element_text(hjust = .5),
        plot.subtitle = element_text(hjust = .5)) + 
  scale_color_brewer(palette="Set1")

acc_plot_partial

ggsave(filename = "../notes/figures/sadinle_sim_plot_partial.png",
       plot = acc_plot_partial)

```

```{r}
levels <- cd[[4]]
P <- prod(levels) 
var_names <- cd$compFields[,1]
ProcessChain <- function(samps){
  avg <- apply(samps, 1, mean)
  upper <- apply(samps, 1, function(x){
    quantile(x, .975)
  })
  lower <- apply(samps, 1, function(x){
    quantile(x, .025)
  })
  params <- factor(unlist(sapply(levels, seq_len)))
  field <- factor(unlist(mapply(function(x, y) {
    rep(x, y)
  }, x = var_names, y = levels)), levels = var_names)
  
  data.frame(params, field, avg, upper, lower)
}

# m trace
m_fabl <- ProcessChain(Zchain$m)
m_fabl$method <- "fabl"
df <- data.frame(m_fabl)

df %>% 
  ggplot(aes(x = params, y = avg,
             ymin = lower, ymax = upper)) +
  geom_pointrange() +
  facet_wrap(~field, scales = "free_x") + 
  labs(y = "Probability",
       x = "Agreement Level",
       color = "Method") + 
  theme_bw() + 
  scale_color_brewer(palette="Set1")

#ggsave("../notes/figures/el_salvador/m_posterior_smallP.png")

m_tidy <- lapply(seq_len(dim(Zchain$m)[1]), function(x){
  data.frame(Zchain$m[x, ], m_fabl[x, 1], m_fabl[x, 2])
}) %>% 
  do.call(rbind, .)

colnames(m_tidy) <- c("value", "level", "field")
m_tidy <- m_tidy %>% 
  group_by(field, level) %>% 
  mutate(iteration = row_number()) %>% 
  ungroup()

m_trace <- m_tidy %>% 
  ggplot(aes(x = iteration, y = value)) +
  facet_grid(level ~ field) + 
  geom_line() +
  labs(x = NULL, y = NULL) +
  scale_x_continuous(labels = NULL, breaks = NULL)

m_trace

ggsave("../notes/figures/sim_m_trace.png", plot = m_trace)

```
```{r}

# u trace
u_fabl <- ProcessChain(Zchain$u)
u_fabl$method <- "fabl"
df <- data.frame(u_fabl)

df %>% 
  ggplot(aes(x = params, y = avg,
             ymin = lower, ymax = upper)) +
  geom_pointrange() +
  facet_wrap(~field, scales = "free_x") + 
  labs(y = "Probability",
       x = "Agreement Level",
       color = "Method") + 
  theme_bw() + 
  scale_color_brewer(palette="Set1")

#ggsave("../notes/figures/el_salvador/m_posterior_smallP.png")

u_tidy <- lapply(seq_len(dim(Zchain$u)[1]), function(x){
  data.frame(Zchain$u[x, ], u_fabl[x, 1], u_fabl[x, 2])
}) %>% 
  do.call(rbind, .)

colnames(u_tidy) <- c("value", "level", "field")
u_tidy <- u_tidy %>% 
  group_by(field, level) %>% 
  mutate(iteration = row_number()) %>% 
  ungroup()

u_trace <- u_tidy %>% 
  ggplot(aes(x = iteration, y = value)) +
  facet_grid(level ~ field) + 
  geom_line() +
  labs(x = NULL, y = NULL) +
  scale_x_continuous(labels = NULL, breaks = NULL)

u_trace

ggsave("../notes/figures/sim_u_trace.png", plot = u_trace)



```
```{r}
overlap <- apply(Zchain[[1]], 2, function(x){
  sum(x < n2 + 1)
})
df <- data.frame(overlap)
df$method <- "fabl"
#df <- data.frame(overlap_samples_fabl)
df <- df %>% 
  mutate(iteration = row_number())

overlap_trace <- df %>% 
  filter(method == "fabl") %>% 
  ggplot(aes(x = iteration, y = overlap)) +
  geom_line() + 
  labs(x = NULL, 
       y = NULL) +
  theme_bw()

overlap_trace

ggsave("../notes/figures/sim_overlap_trace.png", plot = overlap_trace)
```

